apiVersion: v1
kind: Deployment
metadata:
  name: first-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: first-app
  template: 
    metadata:
      labels:
        app: first-app
    spec: 
      containers:
        - name: dockerapi_cont
          image: 171717bekesy/dockerapi
